name: "dispatch-test"
on:
  workflow_dispatch
jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Greeting
      run: |
        sleep 20
        echo "hello"
        sleep 5
        echo "there"
